Repository zama-ai/kms, pull requests merged in 2025-09, with the labels that each got.

#97 chore: update tracing-subscriber
  .github/workflows/global-common-workflow.yml
  Cargo.lock
  Cargo.toml
Labels: cla-signed

#92 fix(ci): Add convention to ci workflow
  .github/workflows/check-rust-stable-version.yml
  .github/workflows/ci_lint.yml
  .github/workflows/codeql.yml
  .github/workflows/common-docker-big-instance.yml
  .github/workflows/common-nitro-enclave.yml
  .github/workflows/common-release-workspace-cargo.yml
  .github/workflows/common-testing-big-instance.yml
  .github/workflows/common-testing.yml
  .github/workflows/common-update-argocd.yml
  .github/workflows/dependencies_analysis.yml
  .github/workflows/global-common-workflow.yml
  .github/workflows/helm-lint.yml
  .github/workflows/helm-release.yml
  .github/workflows/helm-test.yml
  .github/workflows/npm-release.yml
  .github/workflows/on-release-images.yml
  .github/workflows/release.yml
  .github/workflows/sync-on-push.yml
  .github/workflows/workflow-pr-dockerfile.yml
  .github/workflows/workflow-pr-test-enclave.yml
Labels: cla-signed

#55 feat(chart): add support for backup vault config
  charts/kms-core/Chart.yaml
  charts/kms-core/templates/_helpers.tpl
  charts/kms-core/templates/kms-core-client-cronjob.yaml
  charts/kms-core/templates/kms-core-client-statefulset.yaml
  charts/kms-core/templates/kms-core-configmap.yaml
  charts/kms-core/templates/kms-core-statefulset.yaml
  charts/kms-core/templates/kms-gen-cert-and-keys-job.yaml
  charts/kms-core/values-example-local.yaml
  charts/kms-core/values.yaml
Labels: cla-signed

#101 chore: ensure centralized CRS gen does not use tau=0
  core/threshold/src/execution/zk/ceremony.rs
Labels: cla-signed

#102 chore: update test param to use v2 crs
  Cargo.lock
  Cargo.toml
  core/service/src/client/crs_gen.rs
  core/service/src/client/tests/centralized/crs_gen_tests.rs
  core/service/src/client/tests/threshold/crs_gen_tests.rs
  core/threshold/src/execution/tfhe_internals/parameters.rs
Labels: cla-signed

#112 chore: make crs ceremony tests serial since they're computation heavy
  .github/workflows/global-common-workflow.yml
  core/threshold/src/execution/zk/ceremony.rs
Labels: cla-signed

#110 feat(charts): allow enabling metrics without enabling traces forwarding
  charts/kms-core/Chart.yaml
  charts/kms-core/templates/kms-core-configmap.yaml
Labels: cla-signed

#116 fix(kms-core): add coverage input
  .config/nextest.toml
  .github/workflows/ci_lint.yml
  .github/workflows/codeql.yml
  .github/workflows/common-docker-big-instance.yml
  .github/workflows/common-nitro-enclave.yml
  .github/workflows/common-testing-big-instance.yml
  .github/workflows/common-testing.yml
  .github/workflows/dependencies_analysis.yml
  .github/workflows/helm-release.yml
  .github/workflows/main.yml
  .github/workflows/npm-release.yml
  .github/workflows/on-release-images.yml
  .github/workflows/release.yml
  .github/workflows/test-reporter.yml
  .github/workflows/workflow-pr-dockerfile.yml
  .github/workflows/workflow-pr-test-enclave.yml
Labels: cla-signed

#125 fix(kms-core): fix nextest test thread
  .github/workflows/common-testing-big-instance.yml
  .github/workflows/common-testing.yml
  .github/workflows/main.yml
Labels: cla-signed

#126 fix(kms-core): fix nextest for main
  .github/workflows/common-testing.yml
Labels: cla-signed

#118 fix: prevent silent overwriting of data
  core/service/src/vault/storage/file.rs
  core/service/src/vault/storage/mod.rs
  core/service/src/vault/storage/ram.rs
  core/service/src/vault/storage/s3.rs
Labels: cla-signed

#131 fix(kms-core): add lfs bool for checkout
  .github/workflows/sync-on-push.yml
Labels: cla-signed

#135 fix: fix sync tags
  .github/workflows/sync-on-push.yml
Labels: cla-signed

#132 chore: deps risks assesment, reordering and annotation
  Cargo.lock
  Cargo.toml
  bc2wrap/Cargo.toml
  core-client/Cargo.toml
  core-client/src/lib.rs
  core-client/tests-utils/Cargo.toml
  core/grpc/Cargo.toml
  core/service/Cargo.toml
  core/service/src/vault/storage/s3.rs
  core/service/tests-utils/Cargo.toml
  core/threshold/Cargo.toml
  core/threshold/src/execution/keyset_config.rs
  core/threshold/src/networking/sending_service.rs
  observability/Cargo.toml
  tools/kms-health-check/Cargo.toml
Labels: documentation, cla-signed, Security Critical

#139 chore: bump version to v0.11.1
  Cargo.lock
  Cargo.toml
  backward-compatibility/Cargo.toml
  backward-compatibility/src/data_0_11.rs
Labels: cla-signed

#144 fix: fx npm release permission
  .github/workflows/common-testing-big-instance.yml
  .github/workflows/npm-release.yml
Labels: cla-signed

#145 fix: fix test reporter exit
  .github/workflows/test-reporter.yml
Labels: cla-signed

#141 fix: enable default kms features in health-check
  tools/kms-health-check/Cargo.toml
Labels: cla-signed

#148 fix(ci): fix wf for enclave
  .github/workflows/workflow-pr-test-enclave.yml
Labels: cla-signed

#140 chore: change core client to support both 1 and more servers
  core-client/config/client_local_centralized.toml
  core-client/config/client_local_threshold.toml
  core-client/src/lib.rs
  core-client/tests-utils/src/lib.rs
  core/service/src/client/tests/centralized/public_decryption_tests.rs
  core/service/src/client/tests/centralized/user_decryption_tests.rs
  core/service/src/client/tests/common.rs
  core/service/src/client/tests/threshold/public_decryption_tests.rs
  core/service/src/client/tests/threshold/user_decryption_tests.rs
  core/service/src/util/key_setup/test_tools.rs
Labels: cla-signed, devops

#153 chore: print information about tokio and rayon threads
  core/service/src/bin/kms-server.rs
Labels: docker, cla-signed

#158 fix: remove locking fhe key check and replace with cache refresh
  core/service/src/engine/threshold/service/public_decryptor.rs
  core/service/src/engine/threshold/service/user_decryptor.rs
Labels: docker, cla-signed

#154 chore(core-client): use compression and sns-precompute as default
  core-client/src/lib.rs
  core-client/tests/integration_test.rs
  core/service/docker-compose.yml
  docs/guides/core_client.md
  toolchain.txt
Labels: cla-signed, devops

#162 fix!: digest order and centralized preproc
  core/grpc/build.rs
  core/grpc/proto/kms.v1.proto
  core/grpc/src/rpc_types.rs
  core/service/src/client/key_gen.rs
  core/service/src/engine/centralized/central_kms.rs
  core/service/src/engine/centralized/service/key_gen.rs
  core/service/src/engine/centralized/service/preprocessing.rs
  core/service/src/engine/threshold/service/key_generator.rs
Labels: cla-signed

#165 fix: add missing build of kms-custodian to core/service Dockerfile
  docker/core/service/Dockerfile
Labels: cla-signed

#168 fix: copy custodian binary for core-client image
  docker/core-client/Dockerfile
Labels: cla-signed

#108 chore!: remove placeholders and limit ABI encoding to supported types up to 256 bits
  Cargo.lock
  core-client/tests/integration_test.rs
  core/grpc/Cargo.toml
  core/grpc/src/lib.rs
  core/grpc/src/rpc_types.rs
  core/service/src/client/tests/centralized/nightly_tests.rs
  core/service/src/client/tests/centralized/public_decryption_tests.rs
  core/service/src/client/tests/common.rs
  core/service/src/client/tests/threshold/nightly_tests.rs
  core/service/src/client/tests/threshold/user_decryption_tests.rs
  core/service/src/engine/base.rs
Labels: cla-signed

#161 fix(chart): add changes for core client v0.12.0
  charts/kms-core/Chart.yaml
  charts/kms-core/templates/kms-core-client-configmap.yaml
  charts/kms-core/templates/kms-core-client-cronjob.yaml
  charts/kms-core/templates/kms-core-client-statefulset.yaml
  charts/kms-core/templates/kms-gen-keys-configmap.yaml
  charts/kms-core/templates/kms-gen-keys-job.yaml
Labels: cla-signed, devops, chart

#170 fix(security): remove old terraform deployment file
  .github/operations/terraform/environments/build/main.tf
Labels: cla-signed

#171 fix(ci): fix core-client configmap with port client
  charts/kms-core/Chart.yaml
  charts/kms-core/templates/kms-core-client-configmap.yaml
  charts/kms-core/templates/kms-gen-keys-configmap.yaml
Labels: cla-signed
