Repository zama-ai/kms, pull requests merged in 2025-08, with the labels that each got.

#42 fix(s3): cleared and improved store/update/delete logic
  core-client/tests-utils/src/lib.rs
  core/service/src/vault/storage/mod.rs
  core/service/src/vault/storage/s3.rs
Labels: bug

#70 fix(ci): fix nitro enclave build
  .github/workflows/common-nitro-enclave.yml
Labels: docker

#83 feat(grpc): add key material availability endpoint
  Cargo.lock
  core/grpc/proto/kms-service-insecure.v1.proto
  core/grpc/proto/kms-service.v1.proto
  core/grpc/proto/kms.v1.proto
  core/service/src/engine/backup_operator.rs
  core/service/src/engine/centralized/endpoint.rs
  core/service/src/engine/mod.rs
  core/service/src/engine/threshold/endpoint.rs
  core/service/src/engine/threshold/service/preprocessor.rs
  core/service/src/engine/threshold/traits.rs
  core/service/src/engine/utils.rs
Labels: cla-signed

#87 chore: improve kms grpc docs regarding error types
  core/grpc/proto/kms-service.v1.proto
  core/grpc/src/utils/tonic_result.rs
  core/service/src/engine/backup_operator.rs
  core/service/src/engine/centralized/endpoint.rs
  core/service/src/engine/centralized/service/context.rs
  core/service/src/engine/centralized/service/crs_gen.rs
  core/service/src/engine/centralized/service/decryption.rs
  core/service/src/engine/centralized/service/key_gen.rs
  core/service/src/engine/context_manager.rs
  core/service/src/engine/threshold/service/crs_generator.rs
  core/service/src/engine/threshold/service/key_generator.rs
  core/service/src/engine/threshold/service/kms_impl.rs
  core/service/src/engine/threshold/service/preprocessor.rs
  core/service/src/engine/threshold/service/public_decryptor.rs
  core/service/src/engine/threshold/service/session.rs
  core/service/src/engine/threshold/service/user_decryptor.rs
  core/service/src/lib.rs
Labels: cla-signed
